// Generated by writeRegistry.ts. Do not edit.
import type {
  BrowserNames,
  BrowserTarget,
  EngineRun,
  FeatureRegistryEntry,
} from '../engine/index';

export const ageWindowTargets: Readonly<Record<string, BrowserTarget>> = {
  "1": {
    "chrome": "139",
    "edge": "139",
    "opera": "121",
    "chrome_android": "139",
    "opera_android": "91",
    "samsunginternet_android": "29.0",
    "webview_android": "139",
    "firefox": "142",
    "firefox_android": "142",
    "safari": "26",
    "safari_ios": "26",
    "webview_ios": "26"
  },
  "2": {
    "chrome": "128",
    "edge": "128",
    "opera": "113",
    "chrome_android": "128",
    "opera_android": "84",
    "samsunginternet_android": "27.0",
    "webview_android": "128",
    "firefox": "129",
    "firefox_android": "129",
    "safari": "18",
    "safari_ios": "18",
    "webview_ios": "18"
  },
  "3": {
    "chrome": "116",
    "edge": "116",
    "opera": "102",
    "chrome_android": "116",
    "opera_android": "77",
    "samsunginternet_android": "23.0",
    "webview_android": "116",
    "firefox": "116",
    "firefox_android": "116",
    "safari": "17",
    "safari_ios": "17",
    "webview_ios": "17"
  },
  "4": {
    "chrome": "104",
    "edge": "104",
    "opera": "90",
    "chrome_android": "104",
    "opera_android": "71",
    "samsunginternet_android": "18.0",
    "webview_android": "104",
    "firefox": "104",
    "firefox_android": "104",
    "safari": "16",
    "safari_ios": "16",
    "webview_ios": "16"
  },
  "5": {
    "chrome": "93",
    "edge": "93",
    "opera": "78",
    "chrome_android": "93",
    "opera_android": "65",
    "samsunginternet_android": "15.0",
    "webview_android": "93",
    "firefox": "91",
    "firefox_android": "91",
    "safari": "15",
    "safari_ios": "15",
    "webview_ios": "15"
  },
  "6": {
    "chrome": "85",
    "edge": "85",
    "opera": "71",
    "chrome_android": "85",
    "opera_android": "60",
    "samsunginternet_android": "13.0",
    "webview_android": "85",
    "firefox": "80",
    "firefox_android": "80",
    "safari": "14",
    "safari_ios": "14",
    "webview_ios": "14"
  },
  "7": {
    "chrome": "76",
    "edge": "79",
    "opera": "63",
    "chrome_android": "76",
    "opera_android": "54",
    "samsunginternet_android": "10.0",
    "webview_android": "76",
    "firefox": "69",
    "firefox_android": "79",
    "safari": "13",
    "safari_ios": "13",
    "webview_ios": "13"
  },
  "8": {
    "chrome": "69",
    "edge": "18",
    "opera": "55",
    "chrome_android": "69",
    "opera_android": "48",
    "samsunginternet_android": "7.4",
    "webview_android": "69",
    "firefox": "62",
    "firefox_android": "62",
    "safari": "12",
    "safari_ios": "12",
    "webview_ios": "12",
    "edge_legacy": "18"
  },
  "9": {
    "chrome": "61",
    "edge": "16",
    "opera": "47",
    "chrome_android": "60",
    "opera_android": "43",
    "samsunginternet_android": "6.0",
    "webview_android": "60",
    "firefox": "55",
    "firefox_android": "55",
    "safari": "11",
    "safari_ios": "11",
    "webview_ios": "11",
    "edge_legacy": "16"
  },
  "10": {
    "chrome": "53",
    "edge": "14",
    "opera": "39",
    "chrome_android": "53",
    "opera_android": "41",
    "samsunginternet_android": "4.2",
    "webview_android": "53",
    "firefox": "48",
    "firefox_android": "48",
    "safari": "10",
    "safari_ios": "10",
    "webview_ios": "10",
    "edge_legacy": "14"
  },
  "11": {
    "chrome": "45",
    "edge": "13",
    "opera": "31",
    "chrome_android": "45",
    "opera_android": "32",
    "samsunginternet_android": "3.2",
    "webview_android": "45",
    "firefox": "40",
    "firefox_android": "40",
    "safari": "9",
    "safari_ios": "9",
    "webview_ios": "9",
    "edge_legacy": "13"
  },
  "12": {
    "chrome": "37",
    "edge": "12",
    "opera": "24",
    "chrome_android": "37",
    "opera_android": "24",
    "samsunginternet_android": "2.0",
    "webview_android": "37",
    "firefox": "32",
    "firefox_android": "32",
    "safari": "8",
    "safari_ios": "8",
    "webview_ios": "8",
    "edge_legacy": "12"
  },
  "13": {
    "chrome": "29",
    "edge": "12",
    "opera": "16",
    "chrome_android": "29",
    "opera_android": "16",
    "samsunginternet_android": "1.5",
    "webview_android": "4.4",
    "firefox": "23",
    "firefox_android": "23",
    "safari": "7",
    "safari_ios": "7",
    "webview_ios": "7",
    "ie": "11",
    "edge_legacy": "12"
  },
  "14": {
    "chrome": "21",
    "edge": "12",
    "opera": "12.1",
    "chrome_android": "25",
    "opera_android": "12.1",
    "samsunginternet_android": "1.0",
    "webview_android": "4.4",
    "firefox": "15",
    "firefox_android": "15",
    "safari": "7",
    "safari_ios": "6",
    "webview_ios": "6",
    "ie": "10",
    "edge_legacy": "12"
  },
  "15": {
    "chrome": "13",
    "edge": "12",
    "opera": "11.6",
    "chrome_android": "18",
    "opera_android": "11.5",
    "samsunginternet_android": "1.0",
    "webview_android": "4",
    "firefox": "6",
    "firefox_android": "6",
    "safari": "6",
    "safari_ios": "5",
    "webview_ios": "5",
    "ie": "10",
    "edge_legacy": "12"
  }
};

export const widelyAvailableTarget: BrowserTarget = {
  "chrome": "121",
  "edge": "121",
  "chrome_android": "121",
  "firefox": "122",
  "firefox_android": "122",
  "safari": "17.2",
  "safari_ios": "17.2"
};


export const engineRuns: Readonly<Record<string, readonly EngineRun[]>> = {
  "chrome": [
    {
      "engine": "WebKit",
      "from": "1"
    },
    {
      "engine": "Blink",
      "from": "28"
    }
  ],
  "edge": [
    {
      "engine": "EdgeHTML",
      "from": "12"
    },
    {
      "engine": "Blink",
      "from": "79"
    }
  ],
  "firefox": [
    {
      "engine": "Gecko",
      "from": "1"
    }
  ],
  "safari": [
    {
      "engine": "WebKit",
      "from": "1"
    }
  ],
  "opera": [
    {
      "engine": "Presto",
      "from": "7"
    },
    {
      "engine": "Blink",
      "from": "15"
    }
  ],
  "ie": [
    {
      "engine": "Trident",
      "from": "8"
    }
  ],
  "chrome_android": [
    {
      "engine": "WebKit",
      "from": "18"
    },
    {
      "engine": "Blink",
      "from": "28"
    }
  ],
  "firefox_android": [
    {
      "engine": "Gecko",
      "from": "4"
    }
  ],
  "safari_ios": [
    {
      "engine": "WebKit",
      "from": "1"
    }
  ],
  "samsunginternet_android": [
    {
      "engine": "WebKit",
      "from": "1.0"
    },
    {
      "engine": "Blink",
      "from": "1.5"
    }
  ],
  "opera_android": [
    {
      "engine": "Presto",
      "from": "10.1"
    },
    {
      "engine": "WebKit",
      "from": "14"
    },
    {
      "engine": "Blink",
      "from": "15"
    }
  ],
  "webview_android": [
    {
      "engine": "WebKit",
      "from": "1"
    },
    {
      "engine": "Blink",
      "from": "4.4"
    }
  ],
  "webview_ios": [
    {
      "engine": "WebKit",
      "from": "1"
    }
  ]
};

export const browserLabels: BrowserNames = {
  "chrome": "Chrome",
  "edge": "Edge",
  "opera": "Opera",
  "chrome_android": "Chrome Android",
  "opera_android": "Opera Android",
  "samsunginternet_android": "Samsung Browser",
  "webview_android": "WebView Android",
  "firefox": "Firefox",
  "firefox_android": "Firefox for Android",
  "safari": "Safari",
  "safari_ios": "Safari on iOS",
  "webview_ios": "WebView on iOS",
  "ie": "Internet Explorer",
  "edge_legacy": "Edge Legacy"
};

export const featureRegistry: readonly FeatureRegistryEntry[] = [
  {
    "id": "css-anchor-name",
    "name": "anchor-name property",
    "kind": "css-property",
    "syntax": "anchor-name",
    "bcdPath": "css.properties.anchor-name",
    "webFeatureId": "anchor-positioning",
    "defaultRisk": "breaks",
    "fallback": "Anchor positioning is ignored and the element falls back to normal positioned layout, usually in the wrong place. Give it usable static coordinates.",
    "baseline": "limited",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/anchor-name",
    "support": {
      "chrome": "125",
      "edge": "125",
      "opera": "111",
      "chrome_android": "125",
      "opera_android": "83",
      "samsunginternet_android": "27.0",
      "webview_android": "125",
      "firefox": "147",
      "firefox_android": "147",
      "safari": "26",
      "safari_ios": "26",
      "webview_ios": "26"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-appearance",
    "name": "appearance property",
    "kind": "css-property",
    "syntax": "appearance",
    "bcdPath": "css.properties.appearance",
    "webFeatureId": "appearance",
    "defaultRisk": "degrades",
    "fallback": "The control keeps its native platform styling, so custom borders and arrows on selects and checkboxes are ignored.",
    "baseline": "widely",
    "baselineDate": "2024-09-14",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/appearance",
    "support": {
      "chrome": "84",
      "edge": "84",
      "opera": "70",
      "chrome_android": "84",
      "opera_android": "60",
      "samsunginternet_android": "14.0",
      "webview_android": "84",
      "firefox": "80",
      "firefox_android": "80",
      "safari": "15.4",
      "safari_ios": "15.4",
      "webview_ios": "15.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-backdrop-filter",
    "name": "backdrop-filter property",
    "kind": "css-property",
    "syntax": "backdrop-filter",
    "bcdPath": "css.properties.backdrop-filter",
    "webFeatureId": "backdrop-filter",
    "defaultRisk": "degrades",
    "fallback": "The backdrop is not blurred, so overlay text can lose contrast against whatever is behind it. Set a solid or semi-opaque background as well.",
    "baseline": "newly",
    "baselineDate": "2024-09-16",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/backdrop-filter",
    "support": {
      "chrome": "76",
      "edge": "79",
      "opera": "63",
      "chrome_android": "76",
      "opera_android": "54",
      "samsunginternet_android": "12.0",
      "webview_android": "76",
      "firefox": "103",
      "firefox_android": "103",
      "safari": "18",
      "safari_ios": "18",
      "webview_ios": "18"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-clip-path",
    "name": "clip-path property",
    "kind": "css-property",
    "syntax": "clip-path",
    "bcdPath": "css.properties.clip-path",
    "webFeatureId": "clip-path",
    "defaultRisk": "degrades",
    "fallback": "The element renders unclipped as a full rectangle, which can cover content the clip was hiding.",
    "baseline": "widely",
    "baselineDate": "2023-07-21",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/clip-path",
    "support": {
      "chrome": "55",
      "edge": "79",
      "opera": "42",
      "chrome_android": "55",
      "opera_android": "42",
      "samsunginternet_android": "6.0",
      "webview_android": "55",
      "firefox": "3.5",
      "firefox_android": "4",
      "safari": "9.1",
      "safari_ios": "9.3",
      "webview_ios": "9.3"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-color-mix",
    "name": "color-mix() function",
    "kind": "css-value",
    "syntax": "color-mix()",
    "bcdPath": "css.types.color.color-mix",
    "webFeatureId": "color-mix",
    "defaultRisk": "breaks",
    "fallback": "The declaration is invalid and dropped, so the property falls back to its inherited or initial value. Declare a literal color first, then override it with color-mix().",
    "baseline": "widely",
    "baselineDate": "2025-11-09",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Values/color_value/color-mix",
    "support": {
      "chrome": "111",
      "edge": "111",
      "opera": "97",
      "chrome_android": "111",
      "opera_android": "75",
      "samsunginternet_android": "22.0",
      "webview_android": "111",
      "firefox": "113",
      "firefox_android": "113",
      "safari": "16.2",
      "safari_ios": "16.2",
      "webview_ios": "16.2"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-contain-intrinsic-size",
    "name": "contain-intrinsic-size property",
    "kind": "css-property",
    "syntax": "contain-intrinsic-size",
    "bcdPath": "css.properties.contain-intrinsic-size",
    "webFeatureId": "contain-intrinsic-size",
    "defaultRisk": "degrades",
    "fallback": "Placeholder sizing is ignored, which can shift layout as skipped content renders. Reserve space with width and height.",
    "baseline": "widely",
    "baselineDate": "2026-03-18",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/contain-intrinsic-size",
    "support": {
      "chrome": "83",
      "edge": "83",
      "opera": "69",
      "chrome_android": "83",
      "opera_android": "59",
      "samsunginternet_android": "13.0",
      "webview_android": "83",
      "firefox": "107",
      "firefox_android": "107",
      "safari": "17",
      "safari_ios": "17",
      "webview_ios": "17"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-container",
    "name": "@container query",
    "kind": "css-at-rule",
    "syntax": "container",
    "bcdPath": "css.at-rules.container",
    "webFeatureId": "container-queries",
    "defaultRisk": "breaks",
    "fallback": "Everything inside the block is ignored, so the component keeps its unqueried layout. Make that base layout the acceptable one and treat the query as an enhancement.",
    "baseline": "widely",
    "baselineDate": "2025-08-14",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/At-rules/@container",
    "support": {
      "chrome": "105",
      "edge": "105",
      "opera": "91",
      "chrome_android": "105",
      "opera_android": "72",
      "samsunginternet_android": "20.0",
      "webview_android": "105",
      "firefox": "110",
      "firefox_android": "110",
      "safari": "16",
      "safari_ios": "16",
      "webview_ios": "16"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-content-visibility",
    "name": "content-visibility property",
    "kind": "css-property",
    "syntax": "content-visibility",
    "bcdPath": "css.properties.content-visibility",
    "webFeatureId": "content-visibility",
    "defaultRisk": "degrades",
    "fallback": "Rendering is not skipped, so the page paints everything up front. Correct, just slower.",
    "baseline": "newly",
    "baselineDate": "2025-09-15",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/content-visibility",
    "support": {
      "chrome": "85",
      "edge": "85",
      "opera": "71",
      "chrome_android": "85",
      "opera_android": "60",
      "samsunginternet_android": "14.0",
      "webview_android": "85",
      "firefox": "125",
      "firefox_android": "125",
      "safari": "18",
      "safari_ios": "18",
      "webview_ios": "18"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-field-sizing",
    "name": "field-sizing property",
    "kind": "css-property",
    "syntax": "field-sizing",
    "bcdPath": "css.properties.field-sizing",
    "webFeatureId": "field-sizing",
    "defaultRisk": "degrades",
    "fallback": "The control keeps its default fixed size instead of growing with its value. Set a width that reads well when it cannot adapt.",
    "baseline": "newly",
    "baselineDate": "2026-06-16",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/field-sizing",
    "support": {
      "chrome": "123",
      "edge": "123",
      "opera": "109",
      "chrome_android": "123",
      "opera_android": "82",
      "samsunginternet_android": "27.0",
      "webview_android": "123",
      "firefox": "152",
      "firefox_android": "152",
      "safari": "26.2",
      "safari_ios": "26.2",
      "webview_ios": "26.2"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-focus-visible",
    "name": ":focus-visible selector",
    "kind": "css-selector",
    "syntax": ":focus-visible",
    "bcdPath": "css.selectors.focus-visible",
    "webFeatureId": "focus-visible",
    "defaultRisk": "breaks",
    "fallback": "Keyboard users lose the focus ring entirely, which is an accessibility failure. Pair it with a plain :focus rule.",
    "baseline": "widely",
    "baselineDate": "2024-09-14",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Selectors/:focus-visible",
    "support": {
      "chrome": "86",
      "edge": "86",
      "opera": "72",
      "chrome_android": "86",
      "opera_android": "61",
      "samsunginternet_android": "14.0",
      "webview_android": "86",
      "firefox": "85",
      "firefox_android": "85",
      "safari": "15.4",
      "safari_ios": "15.4",
      "webview_ios": "15.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-has",
    "name": ":has() selector",
    "kind": "css-selector",
    "syntax": ":has()",
    "bcdPath": "css.selectors.has",
    "webFeatureId": "has",
    "defaultRisk": "breaks",
    "fallback": "The whole rule is dropped when :has() is unknown. Keep a class-based selector that script or the server applies to the same element.",
    "baseline": "widely",
    "baselineDate": "2026-06-19",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Selectors/:has",
    "support": {
      "chrome": "105",
      "edge": "105",
      "opera": "91",
      "chrome_android": "105",
      "opera_android": "72",
      "samsunginternet_android": "20.0",
      "webview_android": "105",
      "firefox": "121",
      "firefox_android": "121",
      "safari": "15.4",
      "safari_ios": "15.4",
      "webview_ios": "15.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-interpolate-size",
    "name": "interpolate-size property",
    "kind": "css-property",
    "syntax": "interpolate-size",
    "bcdPath": "css.properties.interpolate-size",
    "webFeatureId": "interpolate-size",
    "defaultRisk": "degrades",
    "fallback": "Transitions to and from intrinsic sizes snap instead of animating. The end states are still correct.",
    "baseline": "limited",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/interpolate-size",
    "support": {
      "chrome": "129",
      "edge": "129",
      "opera": "115",
      "chrome_android": "129",
      "opera_android": "86",
      "samsunginternet_android": "28.0",
      "webview_android": "129"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-is",
    "name": ":is() selector",
    "kind": "css-selector",
    "syntax": ":is()",
    "bcdPath": "css.selectors.is",
    "webFeatureId": "is",
    "defaultRisk": "breaks",
    "fallback": "The whole rule is dropped, not just the one selector, so write the branches out separately where support matters.",
    "baseline": "widely",
    "baselineDate": "2023-07-21",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Selectors/:is",
    "support": {
      "chrome": "88",
      "edge": "88",
      "opera": "74",
      "chrome_android": "88",
      "opera_android": "63",
      "samsunginternet_android": "15.0",
      "webview_android": "88",
      "firefox": "78",
      "firefox_android": "79",
      "safari": "14",
      "safari_ios": "14",
      "webview_ios": "14"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-layer",
    "name": "@layer cascade layer",
    "kind": "css-at-rule",
    "syntax": "layer",
    "bcdPath": "css.at-rules.layer",
    "webFeatureId": "cascade-layers",
    "defaultRisk": "breaks",
    "fallback": "The block is dropped and the layered rules disappear, which usually reverses the cascade you designed. Order stylesheets by specificity as a fallback.",
    "baseline": "widely",
    "baselineDate": "2024-09-14",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/At-rules/@layer",
    "support": {
      "chrome": "99",
      "edge": "99",
      "opera": "85",
      "chrome_android": "99",
      "opera_android": "68",
      "samsunginternet_android": "18.0",
      "webview_android": "99",
      "firefox": "97",
      "firefox_android": "97",
      "safari": "15.4",
      "safari_ios": "15.4",
      "webview_ios": "15.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-modal",
    "name": ":modal selector",
    "kind": "css-selector",
    "syntax": ":modal",
    "bcdPath": "css.selectors.modal",
    "webFeatureId": "modal",
    "defaultRisk": "degrades",
    "fallback": "The rule is dropped and the modal keeps its default styling. Target the dialog by its open attribute instead.",
    "baseline": "widely",
    "baselineDate": "2025-03-02",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Selectors/:modal",
    "support": {
      "chrome": "105",
      "edge": "105",
      "opera": "91",
      "chrome_android": "105",
      "opera_android": "72",
      "samsunginternet_android": "20.0",
      "webview_android": "105",
      "firefox": "103",
      "firefox_android": "103",
      "safari": "15.6",
      "safari_ios": "15.6",
      "webview_ios": "15.6"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-nesting",
    "name": "CSS nesting",
    "kind": "css-selector",
    "syntax": "&",
    "bcdPath": "css.selectors.nesting",
    "webFeatureId": "nesting",
    "defaultRisk": "breaks",
    "fallback": "Nested rules are discarded wholesale, so the styles never apply. Flatten them at build time.",
    "baseline": "widely",
    "baselineDate": "2026-06-11",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Selectors/Nesting_selector",
    "support": {
      "chrome": "120",
      "edge": "120",
      "opera": "106",
      "chrome_android": "120",
      "opera_android": "80",
      "samsunginternet_android": "25.0",
      "webview_android": "120",
      "firefox": "117",
      "firefox_android": "117",
      "safari": "17.2",
      "safari_ios": "17.2",
      "webview_ios": "17.2"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-oklch",
    "name": "oklch() color",
    "kind": "css-value",
    "syntax": "oklch()",
    "bcdPath": "css.types.color.oklch",
    "webFeatureId": "oklab",
    "defaultRisk": "breaks",
    "fallback": "The declaration is dropped, which can leave text and background the same color. Declare an sRGB equivalent on the line above.",
    "baseline": "widely",
    "baselineDate": "2025-11-09",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Values/color_value/oklch",
    "support": {
      "chrome": "111",
      "edge": "111",
      "opera": "97",
      "chrome_android": "111",
      "opera_android": "75",
      "samsunginternet_android": "22.0",
      "webview_android": "111",
      "firefox": "113",
      "firefox_android": "113",
      "safari": "15.4",
      "safari_ios": "15.4",
      "webview_ios": "15.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-position-anchor",
    "name": "position-anchor property",
    "kind": "css-property",
    "syntax": "position-anchor",
    "bcdPath": "css.properties.position-anchor",
    "webFeatureId": "anchor-positioning",
    "defaultRisk": "breaks",
    "fallback": "Without an anchor reference the element positions against its containing block instead. Provide static offsets that are acceptable on their own.",
    "baseline": "limited",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/position-anchor",
    "support": {
      "firefox": "151",
      "firefox_android": "151"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-position-area",
    "name": "position-area property",
    "kind": "css-property",
    "syntax": "position-area",
    "bcdPath": "css.properties.position-area",
    "webFeatureId": "anchor-positioning",
    "defaultRisk": "breaks",
    "fallback": "The declaration is dropped and the element keeps its inset values, which are often unset. Set explicit inset properties too.",
    "baseline": "limited",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/position-area",
    "support": {
      "chrome": "129",
      "edge": "129",
      "opera": "115",
      "chrome_android": "129",
      "opera_android": "86",
      "samsunginternet_android": "28.0",
      "webview_android": "129",
      "firefox": "147",
      "firefox_android": "147",
      "safari": "26",
      "safari_ios": "26",
      "webview_ios": "26"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-position-sticky",
    "name": "position: sticky",
    "kind": "css-value",
    "syntax": "sticky",
    "bcdPath": "css.properties.position.sticky",
    "webFeatureId": "sticky-positioning",
    "defaultRisk": "degrades",
    "fallback": "The element falls back to static positioning and scrolls away instead of pinning.",
    "baseline": "widely",
    "baselineDate": "2022-03-19",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/position",
    "support": {
      "chrome": "56",
      "edge": "16",
      "opera": "43",
      "chrome_android": "56",
      "opera_android": "43",
      "samsunginternet_android": "6.0",
      "webview_android": "56",
      "firefox": "32",
      "firefox_android": "32",
      "safari": "13",
      "safari_ios": "13",
      "webview_ios": "13"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-scope",
    "name": "@scope block",
    "kind": "css-at-rule",
    "syntax": "scope",
    "bcdPath": "css.at-rules.scope",
    "webFeatureId": "scope",
    "defaultRisk": "breaks",
    "fallback": "Scoped rules are ignored entirely. Reach the same elements with a wrapper class and descendant selectors.",
    "baseline": "newly",
    "baselineDate": "2025-12-12",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/At-rules/@scope",
    "support": {
      "chrome": "118",
      "edge": "118",
      "opera": "104",
      "chrome_android": "118",
      "opera_android": "79",
      "samsunginternet_android": "25.0",
      "webview_android": "118",
      "firefox": "146",
      "firefox_android": "146",
      "safari": "17.4",
      "safari_ios": "17.4",
      "webview_ios": "17.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-scroll-timeline-name",
    "name": "scroll-timeline-name property",
    "kind": "css-property",
    "syntax": "scroll-timeline-name",
    "bcdPath": "css.properties.scroll-timeline-name",
    "webFeatureId": "scroll-driven-animations",
    "defaultRisk": "degrades",
    "fallback": "Support here is uneven and partly behind flags, so check what the animation looks like when the timeline never advances.",
    "baseline": "limited",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/scroll-timeline-name",
    "support": {
      "chrome": "115",
      "edge": "115",
      "opera": "101",
      "chrome_android": "115",
      "opera_android": "77",
      "samsunginternet_android": "23.0",
      "webview_android": "115",
      "safari": "26",
      "safari_ios": "26",
      "webview_ios": "26"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-starting-style",
    "name": "@starting-style block",
    "kind": "css-at-rule",
    "syntax": "starting-style",
    "bcdPath": "css.at-rules.starting-style",
    "webFeatureId": "starting-style",
    "defaultRisk": "degrades",
    "fallback": "The entry animation is skipped and the element appears at its final state, which is abrupt but never broken.",
    "baseline": "newly",
    "baselineDate": "2024-08-06",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/At-rules/@starting-style",
    "support": {
      "chrome": "117",
      "edge": "117",
      "opera": "103",
      "chrome_android": "117",
      "opera_android": "78",
      "samsunginternet_android": "24.0",
      "webview_android": "117",
      "firefox": "129",
      "firefox_android": "129",
      "safari": "17.5",
      "safari_ios": "17.5",
      "webview_ios": "17.5"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-subgrid",
    "name": "subgrid value",
    "kind": "css-value",
    "syntax": "subgrid",
    "bcdPath": "css.properties.grid-template-columns.subgrid",
    "webFeatureId": "subgrid",
    "defaultRisk": "breaks",
    "fallback": "The track list is invalid and the nested grid stops aligning to its parent. Repeat the parent track definition on the child as a fallback.",
    "baseline": "widely",
    "baselineDate": "2026-03-15",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Guides/Grid_layout/Subgrid",
    "support": {
      "chrome": "117",
      "edge": "117",
      "opera": "103",
      "chrome_android": "117",
      "opera_android": "78",
      "samsunginternet_android": "24.0",
      "webview_android": "117",
      "firefox": "71",
      "firefox_android": "79",
      "safari": "16",
      "safari_ios": "16",
      "webview_ios": "16"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-text-wrap-balance",
    "name": "text-wrap: balance",
    "kind": "css-value",
    "syntax": "balance",
    "bcdPath": "css.properties.text-wrap.balance",
    "webFeatureId": "text-wrap-balance",
    "defaultRisk": "degrades",
    "fallback": "Headings wrap normally instead of being balanced, which is only a typographic difference.",
    "baseline": "newly",
    "baselineDate": "2024-05-13",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/text-wrap",
    "support": {
      "chrome": "114",
      "edge": "114",
      "opera": "100",
      "chrome_android": "114",
      "opera_android": "76",
      "samsunginternet_android": "23.0",
      "webview_android": "114",
      "firefox": "121",
      "firefox_android": "121",
      "safari": "17.5",
      "safari_ios": "17.5",
      "webview_ios": "17.5"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "css-view-transition-name",
    "name": "view-transition-name property",
    "kind": "css-property",
    "syntax": "view-transition-name",
    "bcdPath": "css.properties.view-transition-name",
    "webFeatureId": "view-transitions",
    "defaultRisk": "degrades",
    "fallback": "The transition is skipped and the new state appears immediately. Confirm the instant swap is not visually jarring.",
    "baseline": "newly",
    "baselineDate": "2025-10-14",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/CSS/Reference/Properties/view-transition-name",
    "support": {
      "chrome": "111",
      "edge": "111",
      "opera": "97",
      "chrome_android": "111",
      "opera_android": "75",
      "samsunginternet_android": "22.0",
      "webview_android": "111",
      "firefox": "144",
      "firefox_android": "144",
      "safari": "18",
      "safari_ios": "18",
      "webview_ios": "18"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "html-declarative-shadow-dom",
    "name": "declarative shadow DOM",
    "kind": "html-attribute",
    "syntax": "template[shadowrootmode]",
    "bcdPath": "html.elements.template.shadowrootmode",
    "webFeatureId": "declarative-shadow-dom",
    "defaultRisk": "breaks",
    "fallback": "The template stays inert and its content never renders, so the component is simply missing. Attach the shadow root in script as a fallback.",
    "baseline": "newly",
    "baselineDate": "2024-02-20",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/template#shadowrootmode",
    "support": {
      "chrome": "111",
      "edge": "111",
      "opera": "97",
      "chrome_android": "111",
      "opera_android": "75",
      "samsunginternet_android": "22.0",
      "webview_android": "111",
      "firefox": "123",
      "firefox_android": "123",
      "safari": "16.4",
      "safari_ios": "16.4",
      "webview_ios": "16.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "html-details-name",
    "name": "<details name> exclusive accordion",
    "kind": "html-attribute",
    "syntax": "details[name]",
    "bcdPath": "html.elements.details.name",
    "webFeatureId": "details-name",
    "defaultRisk": "degrades",
    "fallback": "Older browsers ignore the grouping and let every panel open at once, which is usable but not exclusive. Close siblings in script if exclusivity matters.",
    "baseline": "newly",
    "baselineDate": "2024-09-03",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/details",
    "support": {
      "chrome": "120",
      "edge": "120",
      "opera": "106",
      "chrome_android": "120",
      "opera_android": "80",
      "samsunginternet_android": "25.0",
      "webview_android": "120",
      "firefox": "130",
      "firefox_android": "130",
      "safari": "17.2",
      "safari_ios": "17.2",
      "webview_ios": "17.2"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "html-dialog",
    "name": "<dialog> element",
    "kind": "html-element",
    "syntax": "dialog",
    "bcdPath": "html.elements.dialog",
    "webFeatureId": "dialog",
    "defaultRisk": "breaks",
    "fallback": "Without support the dialog renders inline and never traps focus, so ship a scripted modal fallback or keep the dialog hidden until you confirm support.",
    "baseline": "widely",
    "baselineDate": "2024-09-14",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/dialog",
    "support": {
      "chrome": "37",
      "edge": "79",
      "opera": "24",
      "chrome_android": "37",
      "opera_android": "24",
      "samsunginternet_android": "3.0",
      "webview_android": "37",
      "firefox": "98",
      "firefox_android": "98",
      "safari": "15.4",
      "safari_ios": "15.4",
      "webview_ios": "15.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "html-fetchpriority",
    "name": "fetchpriority attribute",
    "kind": "html-attribute",
    "syntax": "img[fetchpriority]",
    "bcdPath": "html.elements.img.fetchpriority",
    "webFeatureId": "fetch-priority",
    "defaultRisk": "degrades",
    "fallback": "The hint is ignored and the browser picks its own priority. Order critical markup and preload tags so the default priority is already close to what you want.",
    "baseline": "newly",
    "baselineDate": "2024-10-29",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/HTML/Reference/Attributes/fetchpriority",
    "support": {
      "chrome": "101",
      "edge": "101",
      "opera": "87",
      "chrome_android": "101",
      "opera_android": "70",
      "samsunginternet_android": "19.0",
      "webview_android": "101",
      "firefox": "132",
      "firefox_android": "132",
      "safari": "17.2",
      "safari_ios": "17.2",
      "webview_ios": "17.2"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "html-inert",
    "name": "inert attribute",
    "kind": "html-attribute",
    "syntax": "[inert]",
    "bcdPath": "html.global_attributes.inert",
    "webFeatureId": "inert",
    "defaultRisk": "breaks",
    "fallback": "Without inert, keyboard focus escapes into content you meant to disable. Manage tabindex and pointer-events for that subtree as well.",
    "baseline": "widely",
    "baselineDate": "2025-10-11",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/inert",
    "support": {
      "chrome": "102",
      "edge": "102",
      "opera": "88",
      "chrome_android": "102",
      "opera_android": "70",
      "samsunginternet_android": "19.0",
      "webview_android": "102",
      "firefox": "112",
      "firefox_android": "112",
      "safari": "15.5",
      "safari_ios": "15.5",
      "webview_ios": "15.5"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "html-loading-lazy",
    "name": "loading attribute",
    "kind": "html-attribute",
    "syntax": "img[loading]",
    "bcdPath": "html.elements.img.loading",
    "webFeatureId": "loading-lazy",
    "defaultRisk": "degrades",
    "fallback": "Unsupported browsers load the resource eagerly. The page still works, it just costs more bandwidth on first paint.",
    "baseline": "widely",
    "baselineDate": "2026-06-19",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/img",
    "support": {
      "chrome": "77",
      "edge": "79",
      "opera": "64",
      "chrome_android": "77",
      "opera_android": "55",
      "samsunginternet_android": "12.0",
      "webview_android": "77",
      "firefox": "75",
      "firefox_android": "79",
      "safari": "15.4",
      "safari_ios": "15.4",
      "webview_ios": "15.4"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "html-popover",
    "name": "popover attribute",
    "kind": "html-attribute",
    "syntax": "[popover]",
    "bcdPath": "html.global_attributes.popover",
    "webFeatureId": "popover",
    "defaultRisk": "breaks",
    "fallback": "Without support the element is never hidden and never promoted to the top layer, so it renders in place on load. Hide it with CSS and toggle it in script instead.",
    "baseline": "newly",
    "baselineDate": "2025-01-27",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/popover",
    "support": {
      "chrome": "114",
      "edge": "114",
      "opera": "100",
      "chrome_android": "114",
      "opera_android": "76",
      "samsunginternet_android": "23.0",
      "webview_android": "114",
      "firefox": "125",
      "firefox_android": "125",
      "safari": "17",
      "safari_ios": "17",
      "webview_ios": "17"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  },
  {
    "id": "html-popovertarget",
    "name": "popovertarget attribute",
    "kind": "html-attribute",
    "syntax": "button[popovertarget]",
    "bcdPath": "html.elements.button.popovertarget",
    "webFeatureId": "popover",
    "defaultRisk": "breaks",
    "fallback": "The button does nothing at all without support. Add a scripted click handler that toggles the target.",
    "baseline": "newly",
    "baselineDate": "2025-01-27",
    "mdnUrl": "https://developer.mozilla.org/docs/Web/HTML/Reference/Elements/button#popovertarget",
    "support": {
      "chrome": "114",
      "edge": "114",
      "opera": "100",
      "chrome_android": "114",
      "opera_android": "76",
      "samsunginternet_android": "23.0",
      "webview_android": "114",
      "firefox": "125",
      "firefox_android": "125",
      "safari": "17",
      "safari_ios": "17",
      "webview_ios": "17"
    },
    "dataVersion": {
      "bcd": "8.0.9",
      "webFeatures": "3.34.3",
      "generatedAt": "2026-07-30T00:00:00.000Z"
    }
  }
];
